### PR TITLE
Add autogenerated TypeScript definitions

### LINKED ISSUE #39: Add TypeScript declarations
See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html. This can be easily generated from `shift-spec`.

### LINKED ISSUE #49: Allow passing `type` property to AST constructors
I think it's worth allowing to pass [an optional and valid, but useless] `type` property to the constructors, so that you could take a node instance and perform a shallow copy by passing it to its own constructor.

E.g. currently `checked.js` doesn't allow this, but I think it's harmless to support and sometimes useful to do:

```js
> a = new AST.LiteralNumericExpression({value:42})
LiteralNumericExpression { type: 'LiteralNumericExpression', value: 42 }
> b = new AST.LiteralNumericExpression(a)
Thrown:
TypeError: Argument to LiteralNumericExpression constructor has wrong keys: expected {value}, got {type, value}
    at new LiteralNumericExpression (C:\Users\Ingvar\shift-ast-js\dist\checked.js:1405:11)
```

This could be particularly useful when constructing Shift node instances from POJO objects.

### PR DESCRIPTION
**Pull request by RReverser**
An alternative way would be to generate TypeScript in the first place, and then Babel could be replaced by just TypeScript which would both transpile down to ES2015 *and* generate valid definitions, but for now went with a less invasive change.

Fixes #39.

### CODE REVIEW

**Comment by bakkot** [comment]
Thanks for doing this! I confess I'm not very familiar with TypeScript, so this is going to be a somewhat incomplete review, but that's OK.

A couple points:

- I notice you only define the `Expression` and `Statement` aggregate types. Is there a reason for this? The [spec](https://github.com/shapesecurity/shift-spec/blob/es2018/spec.idl) defines a bunch of others, which can be very useful - for example, if you accept a Script or Module, you can instead just take a Program.
- Is it possible to test these? Even just testing that it was well-formed TypeScript would make me happy, though testing that the types match the implementations would be better still.

**Comment by bakkot** [comment]
(Also, I don't think this fixes #49?)

**Comment by RReverser** [comment]
@bakkot

1. `Expression` and `Statement` helpers simply mirror what `checked` generator is doing - it's also just defining these two as shorthands. Technically it doesn't matter which ones are defined, as these are just private helpers. **UPD**: Just noticed this wasn't the case and they were exported; fixed it.
2. Yeah, it's possible to test but not sure what would be the best way to do so yet... Just try to construct some basic AST in a TypeScript test file?
3. You're right, wrong issue number. I'll fix that.

BTW, regarding (2) - what do you think about the suggestion to replace Babel with TypeScript? That would kinda eliminate the need to test the generated definitions as they would be created by TS itself from the same source as executable code, and so would be guaranteed to be in sync.

**Comment by michaelficarra** [comment]
GitHub doesn't seem to be respecting the `// Generated by ...` comment pattern for some reason. Can you address it with a `linguist-generated` in a `.gitattributes` file?

**Comment by RReverser** [comment]
Hmm, what do you mean by respecting it?

**Comment by michaelficarra** [comment]
@RReverser It's not auto-collapsed in the "files changed" tab. See [this PR](https://github.com/shapesecurity/shift-ast-js/pull/45/files) as an example.

**Comment by RReverser** [comment]
Interesting, I didn't even know Github supports some manual annotations for that. I thought it just uses size as a heuristics.

**Comment by RReverser** [comment]
That said, it's probably better to review the generated code to in case something looks out of line.

**Comment by RReverser** [comment]
- Rebased and fixed `package.json` conflicts.
 - Fixed issue number in the commit message and the PR description.
 - Marked entire `gen` folder as autogenerated in `.gitattributes` in a separate commit.

**Comment by bakkot** [comment]
> `Expression` and `Statement` helpers simply mirror what checked generator is doing - it's also just defining these two as shorthands.

Well, yeah, but that was just so that the code was shorter. In this case I think it would be actually useful to define and export all of the named types, because I think it would be actually useful to be able to declare a variable of type `Expression` (or `Program` or whatever) even though you can only construct concrete types.

But I don't mind too much either way.

> Yeah, it's possible to test but not sure what would be the best way to do so yet... Just try to construct some basic AST in a TypeScript test file?

Sure, that'd be fine by me.

> what do you think about the suggestion to replace Babel with TypeScript

Strongly opposed, personally.

**Comment by RReverser** [comment]
> Strongly opposed, personally.

Fine by me. Although curious - why? If adding typecheck tests, you need need TypeScript as a dev-dependency anyway, and this way you would need only one of them instead of both Babel and TypeScript (since TypeScript can also transpile ES6 -> ES5 while typechecking).

**Comment by bakkot** [comment]
Mostly I don't want learning TypeScript to be a prerequisite to contributing to Shift, for myself or others. More generally I trust Babel's compiler more than I do TypeScript's.

(Though also maybe we should just drop Babel too - node 4 is EOL, node 6 is EOL next month.)

**Comment by RReverser** [comment]
> Mostly I don't want learning TypeScript to be a prerequisite to contributing to Shift, for myself or others. 

Hmm, but this shouldn't be the problem - TypeScript would be just a generated intermediate artifact, just like current `.js` + `.d.ts`, and not something you actually have to write by hand.

Moreover, you don't even have to generate actual TypeScript syntax if that's the concern. TypeScript compiler supports JSDoc too, so you can generate definitions from regular annotated JavaScript.

Anyway, I'll leave that outside of the scope of this PR, as mentioned in the description, I knew such change would be controversial :)

**Comment by RReverser** [comment]
Added basic test that ensures that constructors in `basic.js` correspond to type definitions.

**Comment by bakkot** [comment]
Hm. It'd be better not to modify the existing test files; I'd prefer to have a new file which `tsc` is run against. And, ideally, negative tests as well as positive - files which fail to typecheck, where that behavior is asserted.

I can push that up myself if you don't find the time in the next couple days.

**Comment by RReverser** [comment]
Negative ones are a bit harder unfortunately, as they require either a separate tool like `dtslint` with own config and non-trivial installation time, or a bunch of `tsc` invocations which would likely end up with non-cross-platform error code checks. 

As for your first point, I think it's better to check the real executable tests rather than invent something custom, since it better represents real-world usage and also makes it easier to notice discrepancies between runtime checks in `checked.js` and static ones in TypeScript. As currently seen in the diff, these places are clearly marked and colocated, and, in fact, already helped me find one discrepancy where typings were wrong!

**Comment by RReverser** [comment]
@bakkot Any chance we could move on with current implementation for now? It works, it's tested, it's not very intrusive and it feels that any further improvements shouldn't be hard to do as separate PRs.

**Comment by bakkot** [comment]
Sorry for not getting back to this in a timely way. I should be able to take another look in the next couple of days.

**Review by bakkot — APPROVED** [review]
Still not thrilled about the testing strategy, but since this has now been open for two months and is otherwise good I'm going to merge it as-is and we can revisit the tests later if we want.

**Comment by Kingwl** [comment]
Should every class declaration implement a common interface `Node`?

**Comment by bakkot** [comment]
@Kingwl That's what we do in [shift-java](https://github.com/shapesecurity/shift-java/blob/8b6abaf59c665f50090f0af68df5e1e6c390e0b2/generated-sources/main/java/com/shapesecurity/shift/es2017/ast/ArrayAssignmentTarget.java).

TypeScript has type aliases, though, so it might make sense to instead make `Node` an alias for a union of all the concrete node types. That way you could do something like

```js
function printNode(node: Node): string {
  switch (node.type) {
    case 'ArrayAssignmentTarget':
      return 'foo';
    [... all other cases ...];
    case 'YieldGeneratorExpression':
      return 'bar';
  }
}
```
and not get an error (at least, I assume so; I don't know very much about TypeScript).

If `Node` were an interface instead, I think you'd need to have `default: throw new Error('unreachable')` to satisfy the type checker. That's what we end up with in Java, anyway.

**Comment by RReverser** [comment]
> and not get an error (at least, I assume so; I don't know very much about TypeScript)

You're correct, a union would be more helpful as it provides exhaustiveness checking and would allow to typecheck separate branches by just doing `switch (node.type)` as you did above.

**Pull request merged**
